"""add dofin selected 

Revision ID: 9be8d31e4238
Revises: b2440fb86910
Create Date: 2024-05-16 23:30:24.875968

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9be8d31e4238"
down_revision = "b2440fb86910"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("dofin_selected", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "dofin_selected")
    # ### end Alembic commands ###
