"""Add unique constraint on symbol and date

Revision ID: b2440fb86910
Revises: 
Create Date: 2024-05-15 09:41:32.050935

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2440fb86910"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("symbol", sa.String(length=15), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("risk_group", sa.String(length=100), nullable=True),
        sa.Column("stock_size", sa.String(length=100), nullable=True),
        sa.Column("priority_level", sa.String(length=100), nullable=True),
        sa.Column("adjustment_coefficient", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "d1",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("average", sa.Float(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=15), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="_symbol_date_uc"),
    )
    op.create_table(
        "finances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("shares_out_standing", sa.BigInteger(), nullable=True),
        sa.Column("free_shares", sa.BigInteger(), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=15), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="_symbol_date_fn"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finances")
    op.drop_table("d1")
    op.drop_table("tickers")
    # ### end Alembic commands ###
