version: '3.6'

services:
  
  
  db:
    image: postgres:latest
    container_name: db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=dofin
    networks:
      - df_network

    ports:
      - "5432:5432"  
    # healthcheck:
    #   test:
    #     ["CMD", "pg_isready", "-U", "dofin"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5  


     
networks:
  df_network:
    driver: bridge

volumes:
  postgres_data:
